{"links": {"self": {"href": "data/repositories/osrf/haptix-comm/pullrequests/32/comments/4836470.json"}, "html": {"href": "#!/osrf/haptix-comm/pull-requests/32/_/diff#comment-4836470"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 32, "links": {"self": {"href": "data/repositories/osrf/haptix-comm/pullrequests/32.json"}, "html": {"href": "#!/osrf/haptix-comm/pull-requests/32"}}, "title": "Advertise `/haptix/gazebo/Read` in hx_responser example program"}, "content": {"raw": "It runs. However, when I exit the responser/request example, if the responser exits first, it prints out an error message \"I do not have a service call registered for topic [@@/haptix/gazebo/Update]\". Looks like this is not the behavior on default (actually, branch fix_link_examples since default currently doesn't compile the examples)", "markup": "markdown", "html": "<p>It runs. However, when I exit the responser/request example, if the responser exits first, it prints out an error message \"I do not have a service call registered for topic [@@/haptix/gazebo/Update]\". Looks like this is not the behavior on default (actually, branch fix_link_examples since default currently doesn't compile the examples)</p>", "type": "rendered"}, "created_on": "2015-01-27T22:33:12.271496+00:00", "user": {"display_name": "Jackie K", "uuid": "{e3d60b62-b7c7-4863-b9b9-cdae9f123cec}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be3d60b62-b7c7-4863-b9b9-cdae9f123cec%7D"}, "html": {"href": "https://bitbucket.org/%7Be3d60b62-b7c7-4863-b9b9-cdae9f123cec%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/ea011fa2919d4bd4568b32b440eda779d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJK-0.png"}}, "nickname": "jacquelinekay", "type": "user", "account_id": "557058:f56c822f-f75c-4665-80f9-6e7764893b9c"}, "updated_on": "2015-01-27T22:33:50.129273+00:00", "type": "pullrequest_comment", "id": 4836470}